### ISSUE TITLE
Error 1040: Function must be implemented.

### ISSUE THREAD

**Issue by mcandre** [jondgoodwin/cone#1]
http://cone.jondgoodwin.com/play/index.html

???

**Comment by jondgoodwin** [comment]
The link you posted is a generic link for the Playground. In order for me to see your code that compiles with that error, you will need to create a link using the Gist or Shorten button, and then paste that in here.

The 1040 error typically means Cone is expecting logic after the signature. It looks for an indented block of lines that follow the function signature or else the logic enclosed in curly braces.
