### ISSUE TITLE
What is the language status?

### ISSUE THREAD

**Issue by codec-abc** [jondgoodwin/cone#12]
Hi,

I find the design of Cone to be very appealing. Yet, it seems that the the core language is not implemented yet. I think stating what features are currently implemented (maybe using boxes in the Readme like [ ]  and [x]) would help people know if they want to dig Cone right away of wait a little bit.

What do you think?

**Comment by jondgoodwin** [comment]
Thank you for the kind words. The core language is not fully implemented yet, as you say. In the last couple of months, I have been focused on filling out the reference documentation on the language features, to act as my design spec for how the language should work on features relevant to the next set of implementation steps. When that is done (soon), I will have headers on the top of each reference page indicating which features are working and which are not. (for example: http://cone.jondgoodwin.com/coneref/refeach.html). I also do have a PLAN.md document on the repo that roughly has what you suggest. So, yes, I think it is a good idea!

**Comment by olleharstedt** [comment]
Bump? :)

**Comment by jondgoodwin** [comment]
For the last ten months, I had to take a break from compiler implementation work to focus entirely on my new job. Now, I am back at it, though at a slower pace.

My current focus is on strengthening the implemented type system, particularly user-defined regions, references, lifetimes and void types. This is in line with a series of blog posts made a year ago.

Thanks for your interest. Let me know if there are more details you are interested in.

**Comment by olleharstedt** [comment]
Thanks!

**Comment by olleharstedt** [comment]
Btw, I'm too working on a language with opt-in safe memory management. Concept here, if you're interested: http://olleharstedt.github.io/programming/2021/04/08/concept-of-memory-safe-gc-opt-out.html :)

**Comment by jondgoodwin** [comment]
Congratulations @olleharstedt on working through your own unique design for accomplishing multi-region memory safety.  It definitely looks like a viable approach. Good luck fleshing it out!
