### ISSUE TITLE
uninitialized imm variable can't be assigned in branches

### ISSUE THREAD

**Issue by phase** [jondgoodwin/cone#15]
The top example in http://cone.jondgoodwin.com/coneref/refif.html shows:
```
fn abs(x i32) i32
  imm result i32;
  if x < 0
    result = -x
  else
    result = x
  result
```
but this [errors with](https://is.gd/GdmVYP):
```
Error 1017: You do not have permission to modify lval
 -->     result = -x
         ^--- work/test.cone:4:5
Error 1017: You do not have permission to modify lval
 -->     result = x
         ^--- work/test.cone:6:5
Unsuccessful compile: 2 errors, 0 warnings
```

Changing `result` to `mut` makes this example work.

**Comment by jondgoodwin** [comment]
I love that compilers can be more clever than their careless inventors. Good catch and thanks for writing it up. It is fixed.
