### ISSUE TITLE
Opening playground in new browser provides broken Hello World.

### ISSUE THREAD

**Issue by mikesamuel** [jondgoodwin/cone#19]
Opening http://cone.jondgoodwin.com/play/index.html in a browser with a blank cache pops up the following program:
```
// Your program goes here...
extern fn print(str *u8)

fn main()
  print("Hello world!")
```

as seen at

![](https://i.imgur.com/KCOtQPu.png)

Note the lack of a `:` after `fn main()` at the cursor in the screenshot.

Hitting the "**Run**" button yields:

```
Error 1040: Function/method must be implemented.
 --> fn main()
     ^--- work/test.cone:4:1
Unsuccessful compile: 1 errors, 0 warnings

Compilation failed.
```

If I choose "Hello, World!" from the dropdown I get a version with the `:` that runs fine and which differs in its leading comment: `// Hello World!`

```
Compile finished in 0.0041467 sec (155 kb). 0 warnings detected

Hello world!

Program ended.
```

Once I've selected the working version from the dropdown, reloading the page will restart with the version with the colon.

**Comment by mikesamuel** [comment]
I think I filed this in the wrong repo.  Apologies.

**Comment by jondgoodwin** [comment]
Thanks for spotting and fixing it!
