### ISSUE TITLE
Missing examples for memory management?

### ISSUE THREAD

**Issue by olleharstedt** [jondgoodwin/cone#21]
It would be nice if this page could contain a couple of examples or snippets: https://cone.jondgoodwin.com/memory.html

**Comment by jondgoodwin** [comment]
Appreciate the feedback. I agree that would be a good idea.

Until that happens, you can look at the ["References"](https://cone.jondgoodwin.com/coneref/refrefs.html) section of the Cone reference documentation. It has quite a few examples.
