### ISSUE TITLE
A coule of questions

### ISSUE THREAD

**Issue by rempas** [jondgoodwin/cone#23]
Hi! Cone seems a pretty interesting language and I would like to make some questions if you don't mind.

1. What's the compilation speed of Cone compared to other compilers like GCC, LDC, Rust, Vox, TCC etc. I'm talking about compilation with full optimizations on.
2. What's the runtime performance compared to "gcc -O3"? How many times slower in the worse, average and best cases? Well maybe worse case is enough...
3. How would you call the future of Cone? Do you plan on supporting the project and make it into a fully industry scale language that will be used be millions or you may abandon it sooner or later?
4. Cone targets 3D and promotes how good it is in the 3D scene, does this mean that Cone will be weak in general tasks like Desktop apps, embedded, webapps (non-3D), AI etc.? Do you recommend against the use of Cone in everything non-3D?

Don't get my wrong, I really care about all that, it's not some random questions I made to waste your time. Of course, feel free to not answer to any of them or even to all of them and close my issue if you want. In that case, I wish you good luck with the project!

**Comment by jondgoodwin** [comment]
Hi rempas.  Appreciate the kind words.

1. The front-half of the Cone compiler is blazingly fast.  The backend is slower, being LLVM. Put together, this means Cone compiles faster than Rust, but (I am guessing) slower than Vox which has its own backend.
2. Runtime perf should be as fast as any systems language generated by gcc/llvm, and thus competitive with C.
3. Cone is more than a hobby project. I am investing towards an industrial scale language, appropriately funded and with a broad base of contributors. I cannot promise it will reach that goal, but I am in it for the long haul.
4. Although 3D is important to me and to Cone, Cone is a high-level, lean, safe, high performance, general-purpose programming language. It should serve well anywhere a professional programmer wants to build maintainable, perf-scalable programs. The features that make it well suited to 3d, will serve it well in less demanding environments. Its biggest "weakness" is the unfamiliar sophistication of its reference types, which may well cause heartache for people looking for a dynamically-typed or easy-to-learn language.

**Comment by rempas** [comment]
That's awesome!!! I first found Vox and tried to play with it but I wasn't able to enjoy it and stay around as a lot of features I'm missing and there is no library and also we cannot generate object files and use the existing C libraries, only system calls. So yeah I have to re-implement the wheel. Just learned Cone from a comment the maintainer did about memory management and how Cone does it. I want to ask another thing, does Cone have a standard runtime or I should use C libraries?

**Comment by jondgoodwin** [comment]
Cone has no substantive runtime at this time, and just leverages C runtime. Cone does support the use of extern to enable the use of C libraries, so you can define and then link in whatever you want.

I prefer Python-style for readability, but if you prefer to use semi-colons and curly brackets, it supports them as well.

**Comment by rempas** [comment]
> I prefer Python-style for readability, but if you prefer to use semi-colons and curly brackets, it supports them as well.

Oh, I don't mean that I prefer semi-colons and curly brackets. I just said that while I don't like Python-like syntax, I don't like ANY syntax so at least Pyton-like is faster to type. Thanks a lot for you time!
