### ISSUE TITLE
Why a version of LLVM so old is used?

### ISSUE THREAD

**Issue by rempas** [jondgoodwin/cone#24]
Will it not work with a more resent version of LLVM? I can't get the LLVM version 7. Well I can but I have to compile it and It's a pain in the ass to compile LLVM...

**Comment by jondgoodwin** [comment]
New releases of LLVM do generally break backwards compat, so migration to the latest release is not free. To make it worse, my Amazon instance is low on disk space, making forward migration a pain to do. And lastly, my job has left me with very little time to do this maintenance.

I have prioritized getting new functionality working in the language over doing this maintenance, at least in the near-term. You are welcome to see if it works on a more recent version of LLVM, if you want. It might.

**Comment by rempas** [comment]
Oh, I didn't knew about all that. It makes sense now. I will try a newer version and tell you if it is working. Thanks a lot for your work and your time!

**Comment by rempas** [comment]
Ok, I just tried to compile it with the latest stable LLVM version (12) and there was one bug. It goes as follows:

```
/home/rempas/Downloads/cone/src/c-compiler/genllvm/genllvm.c: In function ‘genlPackage’:
/home/rempas/Downloads/cone/src/c-compiler/genllvm/genllvm.c:256:28: error: too few arguments to function ‘LLVMDIBuilderCreateCompileUnit’
  256 |         gen->compileUnit = LLVMDIBuilderCreateCompileUnit(gen->dibuilder, LLVMDWARFSourceLanguageC,
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/rempas/Downloads/cone/src/c-compiler/genllvm/genllvm.h:15,
                 from /home/rempas/Downloads/cone/src/c-compiler/genllvm/genllvm.c:15:
/usr/include/llvm-c/DebugInfo.h:260:17: note: declared here
  260 | LLVMMetadataRef LLVMDIBuilderCreateCompileUnit(
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
That's great because this means that there is only one line of code that needs to be changed in order to have it work with more resent version. So do your thing and you check it when you have time. I hope I could help you win some time! Have a nice day!

P.S. Be the one to close this issue after you read this so I'm sure that you have seen it!

**Comment by jondgoodwin** [comment]
Thanks for checking into it!  That is good news indeed to know the migration is likely to have few issues.

When I have a chance, will definitely do this maintenance.
