### ISSUE TITLE
Delayed initialization code doesn't seem to work for an immutable value

### ISSUE THREAD

**Issue by Ivo-Balbaert** [jondgoodwin/cone#27]
The following code (mentioned in [the Reference](https://cone.jondgoodwin.com/coneref/refterm.html))
doesn't work:

```
fn main():
  imm height f32
  height = 1.86
```

It gives the compiler error:

Error 1017: You do not have permission to modify lval
 -->   height = 1.86
       ^--- test.cone:3:3
Unsuccessful compile: 1 errors, 0 warnings
This compile error occurs for the current Cone version and in the playground.

This works for a mutable (mut) value.
Is there another way to delay initialization of an immutable value?

(Was also mentioned in issue #1)

**Comment by jondgoodwin** [comment]
How silly of me!  This bug is fixed.

Really appreciate you finding this and letting me know!
