### ISSUE TITLE
Better error message needed "expecting semicolon"

### ISSUE THREAD

**Issue by Meai1** [jondgoodwin/cone#3]
> Error 1003: Expected semicolon - skipping forward to find it
>  -->   mut a = &gc Point(1., 2.)

I dont have a Point type in this sample but it doesnt complain about that, instead it only complains about a semicolon? Weird.
```
fn main()
  mut a = &gc Point(1., 2.)
```

**Comment by jondgoodwin** [comment]
&gc is currently not yet supported. The parser therefore assumes that gc must be a variable. Were it a variable, the subsequent Point initializer is a syntax error.

I agree a clearer error message is needed from the parser here.

**Comment by jondgoodwin** [comment]
The syntax for region-based allocation has changed. As a result a better error message is now generated for this example:

```
Error 1019: The name gc does not refer to a declared name
 -->   mut a = +gc Point(1., 2.)
                ^--- test.cone:24:12
```

This issue is thus fixed.
