### ISSUE TITLE
Overloading does not work for operator methods

### ISSUE THREAD

**Issue by Ivo-Balbaert** [jondgoodwin/cone#35]
The following code:

```
struct Point:
  x f64
  y f64
  
  // Subtract two points
  // A `-` method implements the binary subtract ('-') operator
  fn `-`(pt2) Point:
    Point[pt2.x - x, pt2.y - y]

  // Overloading: unary operator
  fn `-`() Point:
    Point[-x, -y]
  
fn main():
  mut pt1 = Point[3d, 0d]
  imm pi1m = -pt1
```

gives the following error at compilation:

Error 1022: Function call requires more arguments than specified
 -->   imm pi1m = -pt1   // Error 1022: Function call requires more arguments than specified
                  ^--- test.cone:16:14
Unsuccessful compile: 1 errors, 0 warnings

It seems that the subtract definition of - is called here, instead of the unary - definition.
Perhaps overloading does not work for operator methods.

**Comment by jondgoodwin** [comment]
What an interesting and subtle bug. Very pleased you found it and it is now squashed.

Please verify and close if you are satisfied.

**Comment by Ivo-Balbaert** [comment]
You squashed it! Over and out.
