### ISSUE TITLE
Implicit self parameter is not treated as mut

### ISSUE THREAD

**Issue by Ivo-Balbaert** [jondgoodwin/cone#36]
The following code compiles:

```
struct Test:
  n u32

  fn inca(a u32):
    n += a
```

but this slight variation in inca:

```
  fn inca(a u32):
    n = a + 1
```

gives the error:

Error 1017: You do not have permission to modify lval
 -->     n = a + 1
         ^--- test.cone:5:5
Unsuccessful compile: 1 errors, 0 warnings

mut n   doesn't change this behavior

The following code compiles:

struct Test:
  n u32

  fn inca(mut self Test, a u32):
    n = a + 1

**Comment by jondgoodwin** [comment]
I gave you bad advice before you filed this issue.

The implicit self parameter is immutable, not mutable. So, both versions of inca should fail with an error, unless one passes a mutable self (as you do at the end).

I fixed it so `n += a` will fail in a similar way to `n= a + 1`. Both now fail.

Feel free to mark this issue resolved, once you are satisfied.

**Comment by Ivo-Balbaert** [comment]
I might have overlooked something, but with my updated conec, this code still compiles:

struct Test:
  n u32

  fn inca(a u32):
    n += a

**Comment by Ivo-Balbaert** [comment]
Ok, the latest compiled conec moved to the folder where it should have been, I get the same error now.
