### ISSUE TITLE
Segmentation fault in printing nil

### ISSUE THREAD

**Issue by Ivo-Balbaert** [jondgoodwin/cone#37]
The following code snippet segfaults at execution. Instead, it should generate an error message. It should be illegal to assign nil to dessert, and print <- nil should be a "function not found" error. 

```
import stdio::*

imm hello = "Hello"

fn main():
  mut dessert = jello(hello)
  print <- dessert // <-- Segmentation fault

fn jello(mut saying [5; u8]):
  saying = "jello"
  saying
```

**Comment by jondgoodwin** [comment]
Fixed. Feel free to close if you agree.

**Comment by Ivo-Balbaert** [comment]
Changing the signature of the jello function to 
fn jello(mut saying [5; u8]) [5; u8]:
now prints out "jello"
All test-files compile and execute.
