### ISSUE TITLE
Problems with the play page

### ISSUE THREAD

**Issue by mauro-balades** [jondgoodwin/cone#38]
I have experienced some problems with the play page on the website. (https://cone.jondgoodwin.com/play/index.html)

The `hello, world`  given as a start gives an error (I don't really know how the syntax is because I just heard of it).

![Screenshot_20211209_163617](https://user-images.githubusercontent.com/91018726/145427013-100020a0-1bee-48a7-be0d-6727ab7b3a80.png)
.

Secondly, I am not able to change the theme and editor.

**Comment by Ivo-Balbaert** [comment]
Hi, I am not the author of the website or the language, but the correct current import syntax is now:    import stdio::*
This makes the code work.
Somehow an old version of the PlayGround starting page can still appear, although I can't reproduce this anymore. It's probably a remnant in a cache somewhere.

**Comment by jondgoodwin** [comment]
Thank you mauro for making me aware of this.  I have fixed it.

As for changing the theme and editor, you are right. These capabilities do not really exist. I adapted the playground from another language, and neither removed nor implemented these features.
