### ISSUE TITLE
Can't create a gist

### ISSUE THREAD

**Issue by mauro-balades** [jondgoodwin/cone#39]
It give me the error saying that I am not conected to internet when I try to create a new gist

**Comment by mauro-balades** [comment]
Sorry, I just realized that there is a repo for the website.

**Comment by jondgoodwin** [comment]
Hi Mauro. Again you are right - the Playground offers the option to create a Gist, but it does not work. As with the inability to change the theme, this is an artifact of having clone other language playground but not yet focused on ensuring all its features are supported for Cone.

Until I do, the "Shorten" button accomplishes a similar purpose (publish a playground context and send to others) and it works.
