### ISSUE TITLE
Run doc example codes in playground locally

### ISSUE THREAD

**Issue by ianxek** [jondgoodwin/cone#42]
Run the code inline in the docs, like they do for Go+ (a run button is displayed when the mouse pointer hovers over the code snippets) :

https://tutorial.goplus.org/hello-world

Copy and paste in a new tab opened with the playground would be a start.

**Comment by jondgoodwin** [comment]
Ever since I saw Go do this, I always knew I wanted to as well.

When the language is further along, this is a worthy document improvement goal. I will tackle it then. 

Thanks!
