### ISSUE TITLE
Compilation only outputs .o file, no errors shown

### ISSUE THREAD

**Issue by Meai1** [jondgoodwin/cone#5]
**Problem:**
Compilation outputs no executable binary, only .o

**Description:**
I dont see any option in the --help to specify a different type of output so I assume it's an error. I searched through all subfolders but there is no hello or a.out file.
./conec ./hello.cone
```
extern fn print(str *u8)

fn main()
  print("HI")
```
  
Enabling stronger logging shows nothing:
```
[pc@localhost cone]$ ./conec -V=4 hello.cone
Compile finished in 0.000000 sec (84 kb). 0 warnings detected
```

**Possible source:**
I compiled LLVM with different options because my output was huge, (>20GB) and I dont have that much disk space. These are my options: (also this is using gcc 8.1)
`cmake  -DCMAKE_INSTALL_PREFIX="/home/pc/workarea/experiments/llvm-7"  -DCMAKE_BUILD_TYPE="MinSizeRel"  -DLLVM_TARGETS_TO_BUILD="host"  -DLLVM_BUILD_TOOLS="NO" -DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=WebAssembly ..
`

strace file if you are interested: 
[strace.txt](https://github.com/jondgoodwin/cone/files/2956302/strace.txt)

**Even if this is somehow my fault** because I used other options, point is that **I need to know why**. Cone itself compiled fine after all.

**Comment by Meai1** [comment]
Ok it seems this is intended, the cone compiler only ever spits out an .o file.
I assumed for some reason that the libconestd.a would provide this but for some reason it does not work:

```
[pc@localhost cone]$ gcc -L/home/pc/workarea/experiments/cone/bin -l:libconestd.a ./hello.o -o hello
./hello.o: In function `main':
hello:(.text+0x7): undefined reference to `print'
collect2: error: ld returned 1 exit status
```

Checking if it has the symbols, yes it does:
```
[pc@localhost bin]$ nm ./libconestd.a 

stdio.c.o:
0000000000000000 T print
000000000000006e T printChar
                 U printf
000000000000004a T printFloat
0000000000000025 T printInt
```

However what does work is to simply compile it myself with gcc manually, so the full working set of commands to run something that was compiled with the Cone compiler is:
./conec ./hello.cone
gcc -c ./src/conestd/stdio.c
gcc stdio.o hello.o -o hello

**Comment by Meai1** [comment]
I still think that Cone should be outputting an actual executable though but that's up to you to decide.

**Comment by jondgoodwin** [comment]
You're correct. At this point in time, the Cone compiler only outputs a single object file, and offers no option for directly generating an executable. If I were to enable this, I would need to add code to the compiler that automatically invoked the correct linker under the covers, which I may do in the future.

In a different repo (conehome), I have a simple script called congo, which acts as a primitive build tool, generating the appropriate executable. Using the congo build tool will become the established way to create executables (handling package management as well), but it has a ways to go to get there.
