### ISSUE TITLE
Fails to print u32

### ISSUE THREAD

**Issue by ianxek** [jondgoodwin/cone#50]
This fails

`print <- "x", 3u32`

**Comment by Ivo-Balbaert** [comment]
In the same way, a strange output Ϩ for the unsigned integer 1000
print <- 1000u, "\n"    // => Ϩ  (should be 1000)

**Comment by Ivo-Balbaert** [comment]
print <- 0xE0u

also doesn't print anything on Windows.
On my WSL Ubuntu, it gives: 

*** stack smashing detected ***: terminated
./compexec.sh: line 6:  1724 Segmentation fault      conec $1
Output:
Ϩ

**Comment by Ivo-Balbaert** [comment]
Also strange output here (from refexpr.html):
  ```
  mut flags = 0xC0u
  flags |= 0x01u          // is 0xC1u
  print <- flags, "\n"    // => Á
 ```

**Comment by jondgoodwin** [comment]
Fixed.
