### ISSUE TITLE
`typedef` fails

### ISSUE THREAD

**Issue by git-yledu** [jondgoodwin/cone#51]
`typedef Vector [10;f32]`
Any typedef really, but the doc says it's been implemented, like:
`typedef myInt i32`

**Comment by jondgoodwin** [comment]
I cannot reproduce this bug.  For example:  https://is.gd/neIF1D

Perhaps I fixed it accidentally. Does it now work for you?

**Comment by git-yledu** [comment]
Put the typedef in a `fn` :
https://cone.jondgoodwin.com/play/index.html?gist=9f2b11c95db98f6a68ce786877e8548d

**Comment by jondgoodwin** [comment]
Ah!  It doesn't belong there!  It must be in the module's global scope.

Revised the documentation to indicate this.

**Comment by git-yledu** [comment]
Should the compiler not say something along those lines ?

**Comment by jondgoodwin** [comment]
It does in fact tell you that the typedef is an error.

What it does not do is recognize that you are asking to do something that is allowable elsewhere and not here.

It is not a ton of extra work for me to modify the compiler to specifically look for typedef here in the parser and say, oh oops that can't be used here. But consistency would then require me to think about everything the programmer could put here out of place, like 'fn', 'struct', 'macro' etc, etc.  It would have to recognize all of these as legitimate somewhere else but not here.

That's a lot of work that probably will be helpful when the compiler is much further along, when it is functionally complete but it needs usability improvements in an overhaul of all the error messages.

Doing that work right now, when there are core features not even done seems like pursuing the wrong priorities, especially when my time to spend on Cone is so limited.
