### ISSUE TITLE
Add support for typed array size

### ISSUE THREAD

**Issue by git-yledu** [jondgoodwin/cone#52]
This should be possible : 

`mut arr [10u8 ; f32]`

in order to add performance when arrays are not large, so only need u8 or similar type for the size.

Same for `mut arr [10u16, 25u8;f32]` to allow mixing types

**Comment by jondgoodwin** [comment]
As discussed in private DMs, neither of these suggestions are likely to ever happen.

There is no perf benefit here by reducing the type size governing the number of elements. 

There can be a perf benefit of storing indices in a smaller memory footprint, but that's not here.
