### ISSUE TITLE
Multidim array type compiles but not usable

### ISSUE THREAD

**Issue by git-yledu** [jondgoodwin/cone#54]
This compiles but then we can't do anything :

`mut M[3,4;f32]`

**Comment by jondgoodwin** [comment]
Fixed. Arrays are not restricted to a single dimension, for now.

**Comment by Ivo-Balbaert** [comment]
I believe this should be: "Arrays are restricted to a single dimension, for now."
because the error is: Error 1046: Array type must have exactly one numeric array dimension
