### ISSUE TITLE
Global arrays are not accessible if not initialized

### ISSUE THREAD

**Issue by git-yledu** [jondgoodwin/cone#56]
Global arrays are not accessible if not initialized, but the same is not true for local arrays :
https://is.gd/ngHQ6M

**Comment by jondgoodwin** [comment]
This is not a bug. This is a feature.

As a part of the safety guardrails, variables should never be read from, if they have not first been given a value. With local variables, we can do data flow analysis to ensure this. With global variables, this is currently not possible.

Until module initializers are implemented, all global variables should be given an initial value.
