### ISSUE TITLE
Show example on how to implement C function calls

### ISSUE THREAD

**Issue by Meai1** [jondgoodwin/cone#6]
Interop with C will probably be the primary way to get real world usefulness out of Cone, so that should be documented in my opinion.
How do I read a file? 
How do I write to a socket? 
How do I walk a directory tree?
etc.
So this is probably done by writing a wrapper around libc/muslc, right?

**General usecases:**
1. pass data or functions into C, get data or functions back
2. make those functions you pass in callable from either side

**Comment by jondgoodwin** [comment]
Yes, the documentation should include a page describing how to do interop with C.

By and large, it is pretty straightforward as Cone can map to C types directly. Function/type declarations need to be defined in Cone files, and will require `extern` to link them in from a library built using C.

I will write this up when I get the chance.

**Comment by jondgoodwin** [comment]
And here it is:  https://cone.jondgoodwin.com/coneref/refinclude.html#extern
