### ISSUE TITLE
SSL certificate on website invalid since Mar 15, 2022

### ISSUE THREAD

**Issue by phorward** [jondgoodwin/cone#63]
Hello, please fix your website's SSL settings on https://cone.jondgoodwin.com/, the SSL certificate is invalid since Mar 15, 2022.

**Comment by jondgoodwin** [comment]
I know about it. Have tried to fix and failed so far, due to upgrade script no longer working.

Work commitments have made it impossible for me to carve out bandwidth to rebuild my server as of yet.

It is my top priority when I do get the time. Thanks for raising the issue!

**Comment by jondgoodwin** [comment]
I fixed this last week.  Sorry for any inconvenience.
