### ISSUE TITLE
Unaccounted for line counting when tokenizing strings

### ISSUE THREAD

**Issue by dccarter** [jondgoodwin/cone#64]
https://github.com/jondgoodwin/cone/blob/231ed874c7845e7553a276e949b70f65add70bc9/src/c-compiler/parser/lexer.c#L389

Looks like when tokenizing strings and discarding new line characters, the `Lexer->linenbr` is not update on new line. The location reported on errors and warning becomes off when this happens, for example

```rust
// Hello world!

import stdio::*

fn main():
  print <- "Adding some line 
    but still same string\n"
    
  print <- "With an \Error"
  
```
Note that the error line is reported as line `8` (it should be `9`) in the output below
```
Error 1001: Invalid escape sequence 'E'
 -->   print <- "With an \Error"
                ^--- work/test.cone:8:12
Unsuccessful compile: 1 errors, 0 warnings
```

**Comment by jondgoodwin** [comment]
Thank you. This was helpful. It has been fixed.
